### ISSUE TITLE
他のプラグインやJSカスタマイズの動作を阻害してる

### ISSUE THREAD

**Issue by swny** [SendGridJP/kintone-sendgrid-plugin#8]
各イベントの最後にeventオブジェクトをreturnしていないので、本プラグインの後に読み込まれた他のプラグイン、JSカスタマイズが動作しません。

**Comment by awwa** [comment]
@swny ご連絡ありがとうございます。
問題の詳細が見えていない状況で恐縮ですが、とりあえずポイントになりそうな箇所でeventをreturnするよう修正してみました。
https://github.com/SendGridJP/kintone-sendgrid-plugin/pull/9/files

これで問題が解決するか様子を見ていただけますか？
新しくビルドしたものは以下からダウンロードできると思います。（バージョン7）
https://github.com/SendGridJP/kintone-sendgrid-plugin/blob/issue8/plugin.zip

問題の解決が確認できたらmasterにマージして正式版としたいと思います。
また、こちらでも現象を再現させてみたいので、大変お手数ですが具体的な再現手順をお知らせいただけますと幸いです。

**Comment by swny** [comment]
@awwa 
ご対応ありがとうございました。
問題は解消いたしました。

再現方法についてkintone内部でのjavascript実行順序が不明なので確実ではないかもしれませんが、こちらの環境では以下の方法で確認できます。

１．SendGridプラグインとサイボウズが配布しているメールワイズプラグインを同じアプリに導入
２．上記2つのプラグインを正しく設定する
３．SendGridプラグインは動作するがメールワイズプラグインは「送信」ボタンを押しても何も起きない。

メールワイズ以外のプラグインでも一覧画面でボタンを押して動作するようなものであれば再現するかと思います。

**Comment by awwa** [comment]
@swny 
ありがとうございました。
正式版としてマージしました。
